In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv("C:/Users/ACER/Documents/DSNHack20/DSN_folds.csv")
df.head().T

,0,1,2,3,4
Applicant_ID,Apcnt_1177608,Apcnt_1048432,Apcnt_992524,Apcnt_1181280,Apcnt_1040360
form_field1,3428,3276,3478,3508,3592
form_field2,0,1.06575,0.91305,0.18075,2.89235
form_field3,2.3648,4.5864,0.4798,0.0694,0.067
form_field4,0,0,0,0,0
form_field5,0,37.7982,0,0,0.603
form_field6,3501,0,130315,275412,74688
form_field7,105419,236901,2.3142e+07,6.10613e+06,6.56204e+06
form_field8,105419,16727,130315,408839,1.4218e+06
form_field9,7.58861e+06,212005,1.28401e+07,1.94831e+07,8.82797e+06
form_field10,372273,236901,2.40464e+07,7.82474e+06,2.01588e+07
form_field11,1.87498e+06,1.07948e+06,195667,1.70071e+06,NaN
form_field12,911816,797839,1.02618e+06,876028,4.03082e+06
form_field13,553547,367994,56405,1.95356e+06,8.32343e+06
form_field14,42404890,16576457,26984930,96374750,28141427
form_field15,1.19505e+08,3.58919e+07,1.63383e+08,1.05865e+08,3.08399e+07
form_field16,0,1,0,0,0
form_field17,0,1,0,0,0
form_field18,0,1,0,0,0
form_field19,2,0,1,2,2
form_field20,3,0,1,2,2
form_field21,118.245,144.42,133.095,43.905,91.185
form_field22,11470.6,15069.2,9075,7408.69,8121.9
form_field23,11475,NaN,9075,8869.35,5487.49
form_field24,566.28,NaN,0,33.045,43.02
form_field25,2103,831,2098.5,3924,2119.5
form_field26,11589,2280,9033,1461,9582
form_field27,7726,NaN,3468,974,6388
form_field28,0,0,426,426,548
form_field29,18981,15330,15696,23178,12501
form_field30,7726,NaN,10464,7726,5170
form_field31,5565,15330,NaN,NaN,12501
form_field32,1014,182,460,1892,836
form_field33,7.3334,0.6666,26.1666,14,1.3334
form_field34,0,0,0,0,0
form_field35,0,0,0,0,0
form_field36,20,94,4,10,14
form_field37,12,4,6,18,8
form_field38,8,86,6,18,10
form_field39,0,0,0,0,0
form_field40,158.375,150.873,NaN,NaN,116.853
form_field41,NaN,NaN,NaN,147.54,126.393
form_field42,0.289476,1.03231,0.20625,0.345719,0
form_field43,9.09,3.03,3.03,7.07,13.13
form_field44,0.2264,0.528312,0.791376,0.525488,0.495736
form_field45,NaN,NaN,1,0,0
form_field46,0,0,0,0,0
form_field47,charge,charge,charge,charge,charge
form_field48,79.4847,52.9415,113.065,118.227,496.229
form_field49,0.594389,6.76611,0.675767,1.87021,2.43955
form_field50,0.178956,0.0127896,0.475825,0.202159,0.3137
default_status,no,no,no,yes,no
kfold,0,0,0,0,0

In [3]:
df.select_dtypes(include=['object']).head()

    Applicant_ID form_field47 default_status
0  Apcnt_1177608       charge             no
1  Apcnt_1048432       charge             no
2   Apcnt_992524       charge             no
3  Apcnt_1181280       charge            yes
4  Apcnt_1040360       charge             no

In [4]:
df["form_field47"].value_counts()

charge     36373
lending    19627
Name: form_field47, dtype: int64

In [5]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
form_field1,53471.0,3.491796e+03,1.884624e+02,2990.000000,3.358000e+03,3.484000e+03,3.620000e+03,3.900000e+03
form_field2,52156.0,5.507368e-01,8.209792e-01,0.000000,7.078750e-02,2.675750e-01,7.195125e-01,1.801505e+01
form_field3,55645.0,1.052225e+00,2.147768e+00,0.000000,0.000000e+00,6.200000e-02,1.282000e+00,5.737160e+01
form_field4,55645.0,8.519789e-01,3.157692e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,9.167220e+01
form_field5,55645.0,1.956317e+00,1.051240e+01,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,4.077486e+02
form_field6,42640.0,6.244479e+05,1.433422e+06,0.000000,1.400400e+04,1.155330e+05,5.259280e+05,5.313546e+07
form_field7,50837.0,6.865210e+06,1.912729e+07,0.000000,6.869740e+05,2.704328e+06,6.993831e+06,2.158794e+09
form_field8,42640.0,2.626690e+06,3.927355e+06,0.000000,1.929440e+05,9.639420e+05,3.751516e+06,1.037397e+08
form_field9,47992.0,1.316002e+07,1.977963e+07,0.000000,1.368502e+06,5.506295e+06,1.694552e+07,3.200533e+08
form_field10,55645.0,1.185585e+07,2.669459e+07,0.000000,4.500730e+05,3.707559e+06,1.326101e+07,2.191361e+09
form_field11,24579.0,2.054715e+06,4.912980e+06,0.000000,2.172565e+05,6.986440e+05,1.964839e+06,1.707430e+08
form_field12,46105.0,2.771113e+06,4.544838e+06,0.000000,2.758010e+05,1.163110e+06,3.360182e+06,1.240439e+08
form_field13,50111.0,6.009944e+06,2.335893e+07,0.000000,1.921660e+05,1.605792e+06,5.593626e+06,2.457824e+09
form_field14,56000.0,6.914875e+07,2.713995e+09,0.000000,1.657646e+07,2.814143e+07,4.818738e+07,3.854990e+11
form_field15,33525.0,1.145041e+08,1.153842e+08,539543.000000,5.007636e+07,8.442428e+07,1.428735e+08,3.456119e+09
form_field16,42964.0,2.304255e-01,6.218333e-01,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,1.100000e+01
form_field17,44849.0,2.656915e-01,7.201984e-01,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,2.100000e+01
form_field18,45598.0,2.718321e-01,7.254342e-01,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,2.100000e+01
form_field19,55996.0,9.487999e-01,1.736454e+00,0.000000,0.000000e+00,0.000000e+00,1.000000e+00,2.800000e+01
form_field20,55645.0,1.031593e+00,1.785122e+00,0.000000,0.000000e+00,0.000000e+00,1.000000e+00,2.900000e+01
form_field21,40146.0,8.650038e+01,5.344553e+01,0.255000,4.030500e+01,8.916750e+01,1.298925e+02,1.957875e+03
form_field22,35600.0,6.628316e+03,5.661059e+03,0.000000,1.068668e+03,5.976225e+03,1.135417e+04,9.720000e+04
form_field23,27877.0,6.452875e+03,5.739969e+03,0.000000,7.971450e+02,5.548935e+03,1.128000e+04,9.720000e+04
form_field24,42703.0,1.045585e+02,4.366707e+02,0.000000,1.486500e+01,6.066000e+01,1.147125e+02,3.186375e+04
form_field25,50550.0,2.624556e+03,1.964227e+03,0.000000,1.231500e+03,2.203500e+03,3.517500e+03,2.509350e+04
form_field26,48562.0,1.010655e+04,8.796472e+03,0.000000,3.375000e+03,8.214000e+03,1.414500e+04,7.327500e+04
form_field27,46701.0,6.190517e+03,5.390915e+03,0.000000,2.068000e+03,5.110000e+03,8.700000e+03,4.252200e+04
form_field28,55645.0,1.727432e+04,2.693074e+04,0.000000,6.000000e+01,4.860000e+02,6.077200e+04,6.077200e+04
form_field29,55645.0,1.651854e+04,9.666184e+03,0.000000,9.765000e+03,1.505700e+04,2.181000e+04,7.391400e+04
form_field30,30491.0,5.213247e+03,3.124491e+03,0.000000,2.312000e+03,5.658000e+03,7.726000e+03,2.555000e+04
form_field31,16592.0,1.085757e+04,6.049678e+03,0.000000,6.297000e+03,1.058400e+04,1.423500e+04,4.708500e+04
form_field32,50550.0,9.383453e+02,1.044597e+03,0.000000,1.940000e+02,5.980000e+02,1.332000e+03,2.130600e+04
form_field33,54744.0,1.392658e+01,1.520840e+01,0.166600,2.333400e+00,7.833400e+00,2.116660e+01,1.520000e+02
form_field34,55645.0,2.302453e-01,6.830629e-01,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,2.100000e+01
form_field35,32852.0,1.998661e-01,5.740017e-01,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+01
form_field36,54005.0,1.285907e+01,1.062198e+01,2.000000,6.000000e+00,1.000000e+01,1.600000e+01,2.000000e+02
form_field37,50550.0,8.480435e+00,9.328810e+00,0.000000,2.000000e+00,6.000000e+00,1.200000e+01,1.060000e+02
form_field38,55645.0,8.601420e+00,7.969215e+00,0.000000,4.000000e+00,6.000000e+00,1.200000e+01,1.560000e+02
form_field39,51789.0,9.084941e-02,4.238022e-01,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,2.100000e+01
form_field40,12271.0,1.477980e+02,4.508589e+01,0.021000,1.361918e+02,1.500000e+02,1.677540e+02,6.454500e+02
form_field41,17771.0,1.081174e+02,3.676577e+01,0.000000,8.705550e+01,1.184415e+02,1.374968e+02,2.550000e+02
form_field42,54677.0,3.682155e-01,4.128584e-01,0.000000,0.000000e+00,2.200000e-01,6.285730e-01,2.200000e+00
form_field43,55432.0,6.634511e+00,6.378946e+00,0.000000,2.020000e+00,5.050000e+00,1.010000e+01,9.191000e+01
form_field44,50617.0,5.633768e-01,1.969729e-01,0.048528,4.116720e-01,5.886480e-01,7.538400e-01,8.000000e-01
form_field45,24683.0,7.251955e-02,2.911457e-01,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,5.000000e+00
form_field46,40096.0,9.537111e-02,3.352099e-01,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,5.000000e+00
form_field48,35111.0,3.052449e+05,1.647757e+06,0.000000,7.710079e+01,3.181243e+02,1.153022e+03,5.321014e+07
form_field49,55645.0,1.049061e+00,1.806160e+00,0.000000,0.000000e+00,0.000000e+00,1.181754e+00,2.800000e+01
form_field50,44944.0,6.005862e+05,5.842405e+06,0.000000,4.560141e-02,1.703996e-01,4.993370e-01,2.307571e+08
kfold,56000.0,2.000000e+00,1.414226e+00,0.000000,1.000000e+00,2.000000e+00,3.000000e+00,4.000000e+00

In [6]:
def data_info(df,pred = None):
    obs = df.shape[0]
    types = df.dtypes
    counts= df.apply(lambda x:x.count())
    uniques=df.apply(lambda x:[x.unique()])
    nulls=df.apply(lambda x : x.isnull().sum())
    distincts=df.apply(lambda x: x.unique().shape[0])
    missing_percent = df.isnull().sum()/obs * 100
    skewness = df.skew()
    kurtosis=df.kurt()
    print("Data shape:",df.shape)
    if pred is None:
        cols = ["types", "counts","distincts","nulls","missing_percent","uniques","skewness","kurtosis"]
        stp = pd.concat([types,counts,distincts,nulls,missing_percent,uniques,skewness,kurtosis],axis=1,sort=True)
    else :
        corr = df.corr()[pred]
        stp = pd.concat([types,counts,distincts,null,skewness,kurtosis,skewness,kurtosis, corr],axis=1,sort=True)
        corr_col = "corr" + pred
        cols = ["types", "counts","distincts","nulls","missing_percent","uniques","skewness","kurtosis",corr_col]
    stp.columns = cols
    dtypes = stp.types.value_counts()
    print("____________________________\nData types:\n",stp.types.value_counts())
    print("____________________________")
    return stp

In [7]:
data_info(df)

Data shape: (56000, 53)
____________________________
Data types:
 float64    48
object      3
int64       2
Name: types, dtype: int64
____________________________

,types,counts,distincts,nulls,missing_percent,uniques,skewness,kurtosis
Applicant_ID,object,56000,56000,0,0.000000,"[[Apcnt_1177608, Apcnt_1048432, Apcnt_992524, ...",NaN,NaN
default_status,object,56000,2,0,0.000000,"[[no, yes]]",NaN,NaN
form_field1,float64,53471,450,2529,4.516071,"[[3428.0, 3276.0, 3478.0, 3508.0, 3592.0, 3472...",0.120458,-0.613786
form_field10,float64,55645,30943,355,0.633929,"[[372273.0, 236901.0, 24046424.0, 7824735.0, 2...",18.007423,981.240131
form_field11,float64,24579,9509,31421,56.108929,"[[1874980.0, 1079475.0, 195667.0, 1700708.0, n...",9.633062,166.233151
form_field12,float64,46105,16779,9895,17.669643,"[[911816.0, 797839.0, 1026182.0, 876028.0, 403...",4.734462,45.782858
form_field13,float64,50111,21961,5889,10.516071,"[[553547.0, 367994.0, 56405.0, 1953558.0, 8323...",53.667658,4860.848413
form_field14,int64,56000,1237,0,0.000000,"[[42404890, 16576457, 26984930, 96374750, 2814...",118.547478,15527.393317
form_field15,float64,33525,23784,22475,40.133929,"[[119504690.0, 35891863.0, 163383112.0, 105865...",5.533132,76.527472
form_field16,float64,42964,12,13036,23.278571,"[[0.0, 1.0, nan, 2.0, 3.0, 4.0, 5.0, 6.0, 8.0,...",3.999875,24.497313
form_field17,float64,44849,16,11151,19.912500,"[[0.0, 1.0, nan, 2.0, 3.0, 4.0, 7.0, 6.0, 5.0,...",5.044450,50.982963
form_field18,float64,45598,17,10402,18.575000,"[[0.0, 1.0, nan, 2.0, 3.0, 4.0, 7.0, 6.0, 5.0,...",4.966005,49.526614
form_field19,float64,55996,27,4,0.007143,"[[2.0, 0.0, 1.0, 3.0, 4.0, 9.0, 6.0, 12.0, 18....",3.327070,18.238157
form_field2,float64,52156,20016,3844,6.864286,"[[0.0, 1.06575, 0.91305, 0.18075, 2.89235, 1.6...",4.299532,34.353007
form_field20,float64,55645,28,355,0.633929,"[[3.0, 0.0, 1.0, 2.0, 4.0, 9.0, 6.0, 12.0, 18....",3.174999,16.783052
form_field21,float64,40146,11102,15854,28.310714,"[[118.245, 144.42000000000004, 133.095, 43.905...",1.714100,43.547447
form_field22,float64,35600,23584,20400,36.428571,"[[11470.59, 15069.225, 9075.0, 7408.695, 8121....",0.799056,3.454026
form_field23,float64,27877,16620,28123,50.219643,"[[11475.0, nan, 9075.0, 8869.349999999999, 548...",0.901040,4.110466
form_field24,float64,42703,12572,13297,23.744643,"[[566.28, nan, 0.0, 33.045, 43.02, 84.21000000...",30.440138,1522.146068
form_field25,float64,50550,5015,5450,9.732143,"[[2103.0, 831.0, 2098.5, 3924.0, 2119.5, 474.0...",1.711413,5.663182
form_field26,float64,48562,595,7438,13.282143,"[[11589.0, 2280.0, 9033.0, 1461.0, 9582.0, 729...",1.471489,2.691958
form_field27,float64,46701,559,9299,16.605357,"[[7726.0, nan, 3468.0, 974.0, 6388.0, 486.0, 8...",1.452973,2.715219
form_field28,float64,55645,96,355,0.633929,"[[0.0, 426.0, 548.0, 60772.0, 1034.0, 60.0, 13...",0.993735,-1.007478
form_field29,float64,55645,655,355,0.633929,"[[18981.0, 15330.0, 15696.0, 23178.0, 12501.0,...",0.933382,1.193729
form_field3,float64,55645,14618,355,0.633929,"[[2.3648, 4.5864, 0.4798, 0.0694, 0.067, 0.0, ...",4.233351,33.556539
form_field30,float64,30491,275,25509,45.551786,"[[7726.0, nan, 10464.0, 5170.0, 608.0, 6326.0,...",0.038387,-0.846308
form_field31,float64,16592,395,39408,70.371429,"[[5565.0, 15330.0, nan, 12501.0, 7482.0, 3285....",0.738210,0.917053
form_field32,float64,50550,2621,5450,9.732143,"[[1014.0, 182.0, 460.0, 1892.0, 836.0, 104.0, ...",2.447196,12.838088
form_field33,float64,54744,555,1256,2.242857,"[[7.3334, 0.6666, 26.1666, 14.0, 1.3334, 8.333...",1.565371,2.681943
form_field34,float64,55645,19,355,0.633929,"[[0.0, 1.0, 2.0, 3.0, 4.0, nan, 5.0, 6.0, 7.0,...",6.205108,78.019000
form_field35,float64,32852,12,23148,41.335714,"[[0.0, 1.0, nan, 2.0, 3.0, 4.0, 9.0, 6.0, 5.0,...",4.167426,25.357885
form_field36,float64,54005,67,1995,3.562500,"[[20.0, 94.0, 4.0, 10.0, 14.0, 8.0, 16.0, 6.0,...",2.634626,14.689391
form_field37,float64,50550,53,5450,9.732143,"[[12.0, 4.0, 6.0, 18.0, 8.0, 0.0, 28.0, 10.0, ...",1.949271,6.692711
form_field38,float64,55645,59,355,0.633929,"[[8.0, 86.0, 6.0, 18.0, 10.0, 14.0, 4.0, 16.0,...",2.722392,18.449534
form_field39,float64,51789,16,4211,7.519643,"[[0.0, nan, 1.0, 2.0, 3.0, 4.0, 6.0, 5.0, 8.0,...",11.814973,299.885030
form_field4,float64,55645,2928,355,0.633929,"[[0.0, 15.291, 0.9, 4.122, 4.3056, 13.77900000...",5.427310,45.488654
form_field40,float64,12271,9849,43729,78.087500,"[[158.3745, 150.87300000000005, nan, 116.853, ...",0.150334,5.995923
form_field41,float64,17771,14376,38229,68.266071,"[[nan, 147.54, 126.39299999999999, 134.5215, 1...",-0.972525,0.193189
form_field42,float64,54677,987,1323,2.362500,"[[0.289476, 1.0323060000000002, 0.20625, 0.345...",1.183635,1.168653
form_field43,float64,55432,60,568,1.014286,"[[9.09, 3.03, 7.07, 13.13, 5.05, 14.14, 4.04, ...",1.638080,4.582548
form_field44,float64,50617,33239,5383,9.612500,"[[0.22640000000000005, 0.528312, 0.79137600000...",-0.438634,-0.930435
form_field45,float64,24683,7,31317,55.923214,"[[nan, 1.0, 0.0, 2.0, 3.0, 4.0, 5.0]]",4.737307,29.612174
form_field46,float64,40096,7,15904,28.400000,"[[0.0, nan, 2.0, 1.0, 3.0, 4.0, 5.0]]",4.031525,19.795214
form_field47,object,56000,2,0,0.000000,"[[charge, lending]]",NaN,NaN
form_field48,float64,35111,32116,20889,37.301786,"[[79.48470961741134, 52.941478975927716, 113.0...",10.552602,167.565151
form_field49,float64,55645,13208,355,0.633929,"[[0.5943889681407513, 6.766110554203067, 0.675...",2.623440,9.891706
form_field5,float64,55645,2992,355,0.633929,"[[0.0, 37.79820000000001, 0.6030000000000001, ...",10.465192,173.981887
form_field50,float64,44944,44747,11056,19.742857,"[[0.17895605485697394, 0.012789587845002837, 0...",15.426124,319.604968
form_field6,float64,42640,5847,13360,23.857143,"[[3501.0, 0.0, 130315.0, 275412.0, 74688.0, 13...",6.203867,87.678098
form_field7,float64,50837,23200,5163,9.219643,"[[105419.0, 236901.0, 23141999.0, 6106133.0, 6...",36.556045,3351.298103
form_field8,float64,42640,12821,13360,23.857143,"[[105419.0, 16727.0, 130315.0, 408839.0, 14217...",3.935070,41.461573
form_field9,float64,47992,22651,8008,14.300000,"[[7588612.0, 212005.0, 12840112.0, 19483065.0,...",3.503331,21.120070
kfold,int64,56000,5,0,0.000000,"[[0, 1, 2, 3, 4]]",0.000000,-1.300009

In [8]:
dft = pd.read_csv("C:/Users/ACER/Documents/DSNHack20/test.csv")

In [9]:
data_info(dft)

Data shape: (24000, 51)
____________________________
Data types:
 float64    48
object      2
int64       1
Name: types, dtype: int64
____________________________

,types,counts,distincts,nulls,missing_percent,uniques,skewness,kurtosis
Applicant_ID,object,24000,24000,0,0.000000,"[[Apcnt_1000032, Apcnt_1000048, Apcnt_1000052,...",NaN,NaN
form_field1,float64,22890,441,1110,4.625000,"[[3236.0, 3284.0, nan, 3232.0, 3466.0, 3408.0,...",0.106462,-0.654839
form_field10,float64,23853,15940,147,0.612500,"[[0.0, 18308285.0, 493641.0, 5752921.0, nan, 4...",7.712529,123.883214
form_field11,float64,10602,5792,13398,55.825000,"[[1649749.0, 622789.0, 118256.0, 1391064.0, 27...",11.127970,201.537846
form_field12,float64,19817,10341,4183,17.429167,"[[5446.0, 1025793.0, nan, 1176725.0, 613064.0,...",7.248238,135.538727
form_field13,float64,21537,12296,2463,10.262500,"[[0.0, 1396510.0, nan, 1220293.0, 4779643.0, 8...",26.590741,1406.750942
form_field14,int64,24000,739,0,0.000000,"[[48187375, 34694910, 21973443, 16576457, 1156...",87.269522,8085.444424
form_field15,float64,14408,10988,9592,39.966667,"[[114686147.0, 87479487.0, nan, 72049802.0, 35...",7.152106,134.859071
form_field16,float64,18526,10,5474,22.808333,"[[0.0, 1.0, nan, 2.0, 4.0, 3.0, 6.0, 5.0, 9.0,...",3.762989,19.944173
form_field17,float64,19305,12,4695,19.562500,"[[0.0, 1.0, nan, 2.0, 4.0, 3.0, 6.0, 5.0, 7.0,...",3.877657,21.333150
form_field18,float64,19631,12,4369,18.204167,"[[0.0, 1.0, nan, 2.0, 4.0, 3.0, 6.0, 5.0, 7.0,...",3.860387,21.219801
form_field19,float64,24000,22,0,0.000000,"[[0.0, 2.0, 3.0, 4.0, 1.0, 8.0, 6.0, 5.0, 7.0,...",3.148875,15.351375
form_field2,float64,22291,11474,1709,7.120833,"[[0.34875, 1.2736, 0.27505, 0.28505, 2.09545, ...",4.485561,44.918549
form_field20,float64,23853,23,147,0.612500,"[[0.0, 2.0, 3.0, nan, 4.0, 5.0, 1.0, 8.0, 6.0,...",3.027137,14.274767
form_field21,float64,17293,8611,6707,27.945833,"[[nan, 142.56, 109.005, 139.065, 146.850000000...",0.578846,3.569837
form_field22,float64,15276,11071,8724,36.350000,"[[nan, 13050.0, 469.29, 2599.995, 5157.885, 13...",0.825323,3.019417
form_field23,float64,11875,7967,12125,50.520833,"[[nan, 469.29, 2599.995, 7627.5, 13689.645, 0....",3.026289,72.980422
form_field24,float64,18395,8903,5605,23.354167,"[[nan, 570.585, 109.005, 15.18, 91.08, 92.175,...",46.621469,3409.701280
form_field25,float64,21744,4036,2256,9.400000,"[[1086.0, 3082.5, nan, 1414.5, 2724.0, 2524.5,...",1.557570,4.163344
form_field26,float64,20828,544,3172,13.216667,"[[6204.0, 10221.0, nan, 4197.0, 9855.0, 6570.0...",1.459010,2.662209
form_field27,float64,20090,507,3910,16.291667,"[[2676.0, 6814.0, nan, 2798.0, 6570.0, 4380.0,...",1.431176,2.616343
form_field28,float64,23853,90,147,0.612500,"[[60.0, 852.0, 182.0, nan, 60772.0, 122.0, 200...",0.952889,-1.087321
form_field29,float64,23853,621,147,0.612500,"[[14691.0, 11955.0, 4836.0, 14964.0, 11679.0, ...",0.933136,1.216059
form_field3,float64,23854,7848,146,0.608333,"[[10.2006, 2.9606, 0.06, 2.8032, 0.8318, nan, ...",4.148587,27.852906
form_field30,float64,13092,251,10908,45.450000,"[[9794.0, 3528.0, nan, 5900.0, 6936.0, 1582.0,...",0.047685,-0.884754
form_field31,float64,7190,374,16810,70.041667,"[[nan, 3558.0, 4836.0, 16059.0, 19710.0, 5019....",0.832887,1.250680
form_field32,float64,21744,2220,2256,9.400000,"[[238.0, 1216.0, nan, 248.0, 2388.0, 332.0, 14...",2.239853,7.943642
form_field33,float64,23505,503,495,2.062500,"[[1.8334, 19.5, 7.8334, 9.0, 16.6666, 11.0, 8....",1.557050,2.504388
form_field34,float64,23853,15,147,0.612500,"[[0.0, 3.0, 1.0, nan, 2.0, 4.0, 6.0, 8.0, 12.0...",5.228412,47.807048
form_field35,float64,14134,10,9866,41.108333,"[[nan, 1.0, 0.0, 2.0, 3.0, 8.0, 4.0, 6.0, 5.0,...",4.043482,23.170819
form_field36,float64,23097,55,903,3.762500,"[[22.0, 30.0, 2.0, 36.0, 24.0, nan, 10.0, 20.0...",2.572168,14.695911
form_field37,float64,21744,48,2256,9.400000,"[[2.0, 18.0, nan, 0.0, 28.0, 30.0, 6.0, 4.0, 8...",2.074253,8.190850
form_field38,float64,23853,45,147,0.612500,"[[14.0, 0.0, 26.0, 20.0, nan, 10.0, 8.0, 6.0, ...",2.809166,24.881633
form_field39,float64,22171,12,1829,7.620833,"[[0.0, 2.0, nan, 1.0, 6.0, 4.0, 3.0, 10.0, 8.0...",9.397616,174.849720
form_field4,float64,23854,1579,146,0.608333,"[[0.0, 9.0198, 2.5182, nan, 0.4644, 12.4272, 6...",13.480333,593.441660
form_field40,float64,5172,4357,18828,78.450000,"[[nan, 144.39600000000004, 148.03799999999995,...",-0.355039,2.511958
form_field41,float64,7651,6768,16349,68.120833,"[[nan, 18.8415, 87.6855, 156.06900000000005, 1...",-0.960456,0.186558
form_field42,float64,23422,779,578,2.408333,"[[0.8250000000000001, 0.507694, nan, 0.916663,...",1.169407,1.115416
form_field43,float64,23750,53,250,1.041667,"[[1.01, 4.04, 0.0, 2.02, 23.23, nan, 12.12, 3....",1.658848,4.903653
form_field44,float64,21638,16543,2362,9.841667,"[[0.8, 0.6232480000000001, nan, 0.464224, 0.72...",-0.449113,-0.925731
form_field45,float64,10462,7,13538,56.408333,"[[nan, 1.0, 0.0, 2.0, 3.0, 4.0, 5.0]]",5.076372,36.114873
form_field46,float64,17115,8,6885,28.687500,"[[0.0, nan, 1.0, 2.0, 3.0, 5.0, 9.0, 19.0]]",11.493721,428.252678
form_field47,object,24000,2,0,0.000000,"[[charge, lending]]",NaN,NaN
form_field48,float64,15078,14096,8922,37.175000,"[[nan, 90.16374224197381, 1303.5871483552698, ...",23.907873,1232.832077
form_field49,float64,23854,6118,146,0.608333,"[[0.0, 0.5049739938393173, 0.7888094236432478,...",2.499103,8.363546
form_field5,float64,23854,1561,146,0.608333,"[[0.0, nan, 12.7188, 1.4256000000000002, 15.07...",9.554707,129.927087
form_field50,float64,19203,19155,4797,19.987500,"[[0.01122099590461203, 0.04352509431714639, na...",15.539675,326.049990
form_field6,float64,18396,3568,5604,23.350000,"[[418564.0, 0.0, nan, 19839.0, 192944.0, 15419...",7.305306,121.257787
form_field7,float64,21769,12968,2231,9.295833,"[[418564.0, 9858816.0, nan, 473802.0, 1150662....",13.044806,367.444987
form_field8,float64,18396,7361,5604,23.350000,"[[418564.0, 49014.0, nan, 473802.0, 1150662.0,...",4.023300,48.987675
form_field9,float64,20600,11707,3400,14.166667,"[[540710.0, 1510098.0, nan, 1724437.0, 7860523...",14.494547,753.708574

In [11]:
df[df["kfold"]==0].default_status.value_counts()

0    11200
Name: default_status, dtype: int64

In [12]:
import joblib
import numpy as np
import pandas as pd
from sklearn import metrics
from sklearn import ensemble
from sklearn import linear_model
from sklearn import preprocessing
from scipy.stats import skew,norm
import warnings
warnings.filterwarnings("ignore")
for fold in range(5):
    df = pd.read_csv("C:/Users/ACER/Documents/DSNHack20/DSN_folds.csv")
    def sta(x):
          if x=='charge':
              
             x=1
          else:
             x=0
          return(x)
    def status(x):
          if x=='yes':
             x=1
          else:
             x=0
          return(x)
    df.default_status = df.default_status.apply(status)
    df.form_field47 = df.form_field47.apply(sta)
    num_col=df.columns.drop(["default_status","Applicant_ID"])
    for c in num_col:
        df[c].fillna(df[c].median(),inplace=True)
    skew_feat = df[num_col].apply(lambda x: skew(x)).sort_values(ascending = False) 
    high_skewed = skew_feat[skew_feat>0.5]
    skew_index = high_skewed.index
    for cols in skew_index:
        df[cols] = np.log1p(df[cols])
    df_train = df[df.kfold != fold].reset_index(drop=True)
    df_valid = df[df.kfold ==fold].reset_index(drop = True)
    sc = preprocessing.StandardScaler()
    df_train[num_col] = sc.fit_transform(df_train[num_col])
    df_valid[num_col] = sc.transform(df_valid[num_col])
    x_train = df_train.drop(["default_status","Applicant_ID","kfold"],axis=1).values
    #x_train = ohe.transform(df_train[features])
    y_train = df_train.default_status.values
    x_valid = df_valid.drop(["default_status","Applicant_ID","kfold"],axis=1).values
    #x_valid = ohe.transform(df_valid[features])
    y_valid = df_valid.default_status.values
    rft = linear_model.LogisticRegression()
    rft.fit(x_train, y_train)
    preds = rft.predict(x_valid)
    result = metrics.roc_auc_score(y_valid, preds)
    #result = np.sqrt(metrics.mean_squared_error(df_valid.Item_Store_Returns.values,preds))
    print(f"Fold={fold}, result = {result}")
print(np.mean(result))
print(np.std(result))
    #joblib.dump(rft,f'C:/Users/ACER/Documents/DSNHack/dt_{fold}.bin')

Fold=0, result = 0.6728749513256809
Fold=1, result = 0.6749341126569783
Fold=2, result = 0.6709633702281762
Fold=3, result = 0.6725202156037937
Fold=4, result = 0.6743382738979645
0.6743382738979645
0.0

In [13]:
sub = pd.read_csv("C:/Users/ACER/Documents/DSNHack20/SampleSubmission.csv")
sub["default_status"].value_counts()

1    24000
Name: default_status, dtype: int64

In [14]:
if __name__ == "__main__":
    dft = pd.read_csv("C:/Users/ACER/Documents/DSNHack20/test.csv")
    def sta(x):
          if x=='charge':
              
             x=1
          else:
             x=0
          return(x)
    dft.form_field47 = dft.form_field47.apply(sta)
    num_col=dft.columns.drop(["Applicant_ID"])
    for c in num_col:
        dft[c].fillna(dft[c].median(),inplace=True)
    skew_feat = dft[num_col].apply(lambda x: skew(x)).sort_values(ascending = False) 
    high_skewed = skew_feat[skew_feat>0.5]
    skew_index = high_skewed.index
    for cols in skew_index:
        dft[cols] = np.log1p(dft[cols])
    dat = dft
    dft = dft.drop(["Applicant_ID"],axis=1)
    predicts = rft.predict_proba(dft)
    sub["default_status"] = predicts
    #submission = pd.DataFrame({"Applicant_ID":dat["Applicant_ID"], "default_status": predicts})
    sub.to_csv("dsn_rft.csv",index = False)

In [15]:
s = pd.read_csv("dsn_rft.csv")
s.head()

    Applicant_ID  default_status
0  Apcnt_1000032             1.0
1  Apcnt_1000048             1.0
2  Apcnt_1000052             1.0
3  Apcnt_1000076             1.0
4  Apcnt_1000080             1.0

In [16]:
s["default_status"].value_counts()

1.0    24000
Name: default_status, dtype: int64